//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Feed.UI.MVCApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>a</string>
  <string>ante</string>
  <string>após</string>
  <string>até</string>
  <string>com</string>
  <string>contra</string>
  <string>de</string>
  <string>desde</string>
  <string>em</string>
  <string>entre</string>
  <string>para</string>
  <string>perante</string>
  <string>por</string>
  <string>sem</string>
  <string>sob</string>
  <string>sobre</string>
  <string>trás</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Prepositions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Prepositions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>o</string>
  <string>os</string>
  <string>a</string>
  <string>as</string>
  <string>um</string>
  <string>uns</string>
  <string>uma</string>
  <string>umas</string>
  <string>ao</string>
  <string>aos</string>
  <string>à</string>
  <string>às</string>
  <string>do</string>
  <string>dos</string>
  <string>da</string>
  <string>das</string>
  <string>dum</string>
  <string>duns</string>
  <string>duma</string>
  <string>dumas</string>
  <string>no</string>
  <string>nos</string>
  <string>na</string>
  <string>nas</string>
  <string>num</string>
  <string>nuns</string>
  <string>numa</string>
  <string>numas</string>
  <string>pelo</string>
  <string>pelos</string>
  <string>pela</string>
  <string>pelas</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Articles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Articles"]));
            }
        }
    }
}
